import os
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from io import BytesIO
import tempfile

class PDFService:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.setup_custom_styles()
    
    def setup_custom_styles(self):
        """Setup custom paragraph styles for the PDF"""
        # Title style
        self.title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER,
            textColor='#2c3e50'
        )
        
        # Chapter heading style
        self.chapter_style = ParagraphStyle(
            'ChapterTitle',
            parent=self.styles['Heading2'],
            fontSize=18,
            spaceBefore=30,
            spaceAfter=18,
            alignment=TA_CENTER,
            textColor='#34495e'
        )
        
        # Body text style
        self.body_style = ParagraphStyle(
            'CustomBody',
            parent=self.styles['Normal'],
            fontSize=12,
            spaceAfter=12,
            alignment=TA_JUSTIFY,
            leftIndent=0,
            rightIndent=0,
            firstLineIndent=20
        )
        
        # Metadata style
        self.meta_style = ParagraphStyle(
            'Metadata',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=6,
            alignment=TA_CENTER,
            textColor='#7f8c8d'
        )
    
    def generate_pdf(self, title, content, author="Penora AI"):
        """Generate PDF from title and content - main method used by routes"""
        # Convert content to chapters format if it's a single string
        if isinstance(content, str):
            # Split content by page headers or use as single chapter
            if 'Page ' in content:
                chapters = content.split('Page ')[1:]  # Skip first empty element
                chapters = ['Page ' + chapter for chapter in chapters]
            else:
                chapters = [content]
        else:
            chapters = content
        
        return self.create_story_pdf(title, chapters, author)

    def create_story_pdf(self, title, chapters, author="Penora AI"):
        """Create a PDF from story chapters"""
        try:
            # Create a temporary file for the PDF
            temp_file = tempfile.NamedTemporaryFile(delete=False, suffix='.pdf')
            temp_filename = temp_file.name
            temp_file.close()
            
            # Create the PDF document
            doc = SimpleDocTemplate(
                temp_filename,
                pagesize=A4,
                rightMargin=72,
                leftMargin=72,
                topMargin=72,
                bottomMargin=18
            )
            
            # Build the story content
            story_content = []
            
            # Add title page
            story_content.append(Spacer(1, 2*inch))
            story_content.append(Paragraph(title, self.title_style))
            story_content.append(Spacer(1, 0.5*inch))
            story_content.append(Paragraph(f"Generated by {author}", self.meta_style))
            story_content.append(Spacer(1, 0.25*inch))
            story_content.append(Paragraph(f"Created with Penora AI", self.meta_style))
            story_content.append(PageBreak())
            
            # Add chapters
            for i, chapter_content in enumerate(chapters, 1):
                # Chapter title
                story_content.append(Paragraph(f"Chapter {i}", self.chapter_style))
                story_content.append(Spacer(1, 0.25*inch))
                
                # Chapter content - split into paragraphs
                paragraphs = chapter_content.strip().split('\n\n')
                for paragraph in paragraphs:
                    if paragraph.strip():
                        # Clean up the paragraph text
                        clean_paragraph = paragraph.strip().replace('\n', ' ')
                        story_content.append(Paragraph(clean_paragraph, self.body_style))
                
                # Add page break after each chapter except the last
                if i < len(chapters):
                    story_content.append(PageBreak())
            
            # Build the PDF
            doc.build(story_content)
            
            # Read the PDF content
            with open(temp_filename, 'rb') as pdf_file:
                pdf_content = pdf_file.read()
            
            # Clean up the temporary file
            os.unlink(temp_filename)
            
            return {
                "success": True,
                "pdf_content": pdf_content,
                "filename": f"{title.replace(' ', '_')}.pdf"
            }
            
        except Exception as e:
            # Clean up on error
            try:
                if 'temp_filename' in locals() and temp_filename and os.path.exists(temp_filename):
                    os.unlink(temp_filename)
            except:
                pass
            
            return {
                "success": False,
                "error": f"Failed to create PDF: {str(e)}"
            }

pdf_service = PDFService()
